cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 21
    exp: 0
    attributePoints: 5
    vitality: 0
    strength: 0
    deft: 15
    arcane: 0
    bonusHealth: 0.0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 1.0
    maxOverhealth: 0.0
    evasion: 0
