cf942050-e942-4990-a113-e3df70b289be:
  stats:
    attributePoints: 8
    vitality: 1
    strength: 0
    deft: 0
    arcane: 0
    maxHealth: 1.0
    currentEnergy: 101.0
    maxEnergy: 101.0
    currentOverhealth: 0.0
    maxOverhealth: 0.0
    physicalDamage: 0
    fireDamage: 0
    coldDamage: 0
    earthDamage: 0
    lightningDamage: 0
    airDamage: 0
    radiantDamage: 0
    necroticDamage: 0
    pureDamage: 0
    critchance: 10
    critdamage: 150
    evasion: 0
    defense: 0
    guard: 0
    physicalResist: 0
    fireResist: 0
    coldResist: 0
    earthResist: 0
    lightningResist: 0
    airResist: 0
    radiantResist: 0
    darkResist: 0
    necroticResist: 0
