cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 100
    exp: 0
    attributePoints: 404
    vitality: 0
    strength: 0
    deft: 0
    arcane: 0
    bonusHealth: 0.0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 0.0
    maxOverhealth: 0.0
    evasion: 0
    physicalDamage: 0
    fireDamage: 0
    coldDamage: 0
    earthDamage: 0
    lightningDamage: 0
    airDamage: 0
    lightDamage: 0
    darkDamage: 0
    pureDamage: 0
