cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 1
    exp: 0.0
    attributePoints: 0
    vitality: 0
    strength: 0
    deft: 0
    arcane: 0
    bonusHealth: 0.0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 0.0
    maxOverhealth: 0.0
    physicalDamage: 0
    fireDamage: 0
    coldDamage: 0
    earthDamage: 0
    lightningDamage: 0
    airDamage: 0
    lightDamage: 0
    darkDamage: 0
    pureDamage: 0
    evasion: 0
    defense: 8
    guard: 15
    physicalResist: 0
    fireResist: 0
    coldResist: 0
    earthResist: 0
    lightningResist: 0
    airResist: 0
    lightResist: 0
    darkResist: 0
