cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 5
    exp: 0
    attributePoints: 0
    vitality: 0
    strength: 0
    deft: 0
    arcane: 4
    bonusHealth: 0.0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 4.0
    maxOverhealth: 4.0
