cf942050-e942-4990-a113-e3df70b289be:
  stats:
    attributePoints: 0
    vitality: 0
    strength: 0
    deft: 0
    arcane: 4
    maxHealth: 0.0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 4.0
    maxOverhealth: 4.0
    physicalDamage: 7
    elementalDamage: 0
    fireDamage: 1
    coldDamage: 0
    earthDamage: 0
    lightningDamage: 0
    airDamage: 0
    radiantDamage: 0
    necroticDamage: 0
    pureDamage: 0
    critchance: 14.0
    critdamage: 170
    evasion: 0
    defense: 0
    guard: 0
    physicalResist: 0
    fireResist: 0
    coldResist: 0
    earthResist: 0
    lightningResist: 0
    airResist: 0
    radiantResist: 0
    necroticResist: 0
