cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 1
    exp: 0
    vitality: 0
    strength: 0
    deft: 0
    arcane: 0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 10.666666666666664
    maxOverhealth: 10.0
