cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 21
    exp: 0
    attributePoints: 20
    vitality: 0
    strength: 0
    deft: 0
    arcane: 0
    bonusHealth: 0.0
    currentEnergy: 100.0
    maxEnergy: 100.0
    currentOverhealth: 5.0
    maxOverhealth: 5.0
