cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 5
    exp: 0
    vitality: 1
    strength: 1
    deft: 1
    arcane: 1
    currentEnergy: 100.0
    maxEnergy: 100.0
    bonusEnergy: 1.0
    currentOverhealth: 0.0
    maxOverhealth: 0.0
    bonusOverhealth: 1.0
    bonusHealth: 1.0
    exp2NextLevel: 100
