cf942050-e942-4990-a113-e3df70b289be:
  stats:
    level: 5
    exp: 0
    vitality: 4
    strength: 0
    deft: 0
    arcane: 0
    currentEnergy: 100.0
    maxEnergy: 100.0
    bonusEnergy: 4.0
    currentOverhealth: 0.0
    maxOverhealth: 0.0
    bonusOverhealth: 0.0
    bonusHealth: 4.0
    exp2NextLevel: 100
