name: NMLPlayerStats
version: '1.0'
main: io.github.NoOne.nMLPlayerStats.NMLPlayerStats
api-version: '1.21'
loadbefore:
  - DamagePlugin
  - NMLWeapons
commands:
  stats:
    description: Opens your stat menu
    usage: /<command>
  resetStats:
    description: Resets your stats
    usage: /<command>